blueprint:
  name: Paralelo Virtual*
  description: Acenda/Apaga todos os switchs/lights do grupo simultaneamente
  domain: automation
  input:
    entrada_switchs:
      name: Escolha os pontos de Iluminação
      selector:
            entity:
              domain:
                - switch
                - light
              multiple: true
    entrada_delay:
      name: Tempo de atraso
      description: Defina o tempo de delay após a operação
      default: 500
      selector:
        number:
          min: 0
          max: 10000
          unit_of_measurement: mili segundos

trigger:
  platform: state
  entity_id: !input entrada_switchs

action:
  - service: >
      {% if trigger.to_state.state == "on" %}
        homeassistant.turn_on
      {% elif trigger.to_state.state == "off" %}
        homeassistant.turn_off
      {% endif %}
    target:
      entity_id:
        !input entrada_switchs
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: !input entrada_delay

mode: single
